ecom/urls.py
from django.urls import path
from ecom.views import index,show_product,show_cart,search

app_name = 'ecom'

urlpatterns = [
	path('',index,name='index'),
	path('product/<int:product_id>/<slug:product_slug>/',show_product, name= 'detail'),
	path('cart/',show_cart, name = 'cart'),
	path('search/',search,name = 'search'),
	]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecom/', include('ecom.urls')),
    path('accounts/',include('registration.backends.default.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
	title = models.CharField(max_length = 100)
	price = models.DecimalField(max_digits = 10, decimal_places = 2)
	slug = models.SlugField()
	description = models.TextField()
	img = models.ImageField(upload_to = '')

	def __str__(self):
		return self.title

class CartItem(models.Model):
	product = models.ForeignKey(Product,on_delete = models.PROTECT)
	cart_id = models.CharField(max_length = 30)
	price = models.DecimalField(max_digits = 10, decimal_places = 2)
	quantity = models.IntegerField()
	timestamp = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return self.product.title

	def update_quantity(self, quantity):
		self.quantity += quantity
		self.save()

	def total_cost(self):
		return self.quantity * self.price

ecom/forms.py
from django import forms

class CartForm(forms.Form):
	quantity = forms.IntegerField(initial = '1')
	product_id = forms.IntegerField(widget = forms.HiddenInput)

	def __init__(self,request,*args,**kwargs):
		self.request = request
		super(CartForm,self).__init__(*args,**kwargs)

ecom/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from ecom.models import Product
from ecom.forms import CartForm
from ecom import cart


# Create your views here.
def index(request):
	p = Product.objects.all()
	context = {'p':p}
	return render(request,'index.html',context)

def show_product(request,product_id,product_slug):
	p = get_object_or_404(Product, id = product_id)

	if request.method == 'POST':
		form = CartForm(request, request.POST)
		if form.is_valid():
			request.form_data = form.cleaned_data
			cart.add_to_cart(request)
			return redirect('ecom:cart')

	form = CartForm(request, initial = {'product_id':product_id})
	context = {'p':p,'form':form}
	return render(request,'detail.html',context)

def show_cart(request):
	if request.method == 'POST':
		item_id = request.POST.get('item_id')
		cart.get_cart_items(request).delete()
	c = cart.get_cart_items(request)
	total = cart.total(request)
	item_count = cart.item_count(request)
	context = {'c':c}
	return render(request,'cart.html',context)

def search(request):
	if request.method == 'GET':
		query = request.GET.get('q')
		s = Product.objects.filter(title__contains = query)
		context = {'s':s}
		return render(request,'search.html',context)
	else:
		return render(request,'search.html')

ecom/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>e-commerce</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <a class="navbar-brand" href="#">
    <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" class="d-block" viewBox="0 0 612 612" role="img" focusable="false"><title>Bootstrap</title><path fill="currentColor" d="M510 8a94.3 94.3 0 0 1 94 94v408a94.3 94.3 0 0 1-94 94H102a94.3 94.3 0 0 1-94-94V102a94.3 94.3 0 0 1 94-94h408m0-8H102C45.9 0 0 45.9 0 102v408c0 56.1 45.9 102 102 102h408c56.1 0 102-45.9 102-102V102C612 45.9 566.1 0 510 0z"></path><path fill="currentColor" d="M196.77 471.5V154.43h124.15c54.27 0 91 31.64 91 79.1 0 33-24.17 63.72-54.71 69.21v1.76c43.07 5.49 70.75 35.82 70.75 78 0 55.81-40 89-107.45 89zm39.55-180.4h63.28c46.8 0 72.29-18.68 72.29-53 0-31.42-21.53-48.78-60-48.78h-75.57zm78.22 145.46c47.68 0 72.73-19.34 72.73-56s-25.93-55.37-76.46-55.37h-74.49v111.4z"></path></svg>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'ecom:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Services
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
      </li>
    </ul>
    <form action = "{% url 'ecom:search' %}" class="form-inline my-2 my-lg-0" method ='GET' value='{{request.GET.q}}'>
      <input class="form-control mr-sm-2" type="search" name = 'q' value = '{{request.GET.q}}' placeholder="Search" aria-label="Search">
    </form>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Cart</button>
  </div>
</nav>
<div class="container">
  {% block content %}
  <!-- Content here -->
  {% endblock %}
</div>

</body>
</html>

ecom/templates/cart.html
{% extends 'base.html' %}

{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Total Cost</th>
    </tr>
  </thead>
  <tbody>
    {% for i in c %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{i.product}}</td>
      <td>{{i.price}}</td>
      <td>{{i.quantity}}</td>
      <td>{{i.total_cost}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
Total : {{total}}<br>
<button type="button" class="btn btn-secondary">Checkout</button>
{% endblock %}

ecom/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="row">
	<div class="col-md-6">
<b>{{p.title}}</b><br>
{{p.description}}<br>
	</div>
	<div class="col-md-6">
<img src="{{p.img.url}}" height="400" width="500"><br>
	</div>
₹{{p.price}}<br>

<form method="post" action="{% url 'ecom:detail' p.id p.slug %}">
	{% csrf_token %}
	{{form}}
	<input class="btn btn-primary" type="submit" value="Add">
</form>

{% endblock %}

ecom/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row">

{% for i in p %}
<div class="col-sm">

<a href="{%url 'ecom:detail' i.pk i.slug %}">{{i.title}}</a><br>
₹{{i.price}}<br>
<br><br>

<img src="{{i.img.url}}" height="300" width="300"><br>

</div>
{% endfor %}

</div>
{% endblock %}

ecom/templates/search.html
{% extends 'base.html' %}

{% block content %}
{%if s %}
<div class="row">

{% for i in s %}
<div class="col-sm">

<a href="{%url 'ecom:detail' i.pk i.slug %}">{{i.title}}</a><br>
₹{{i.price}}<br>
<br><br>

<img src="{{i.img.url}}" height="300" width="300"><br>

</div>
{% endfor %}
{%else%}
<p>no results</p>
{%endif%}

</div>
{% endblock %}